Document: mitogen
Title: Debian mitogen Manual
Author: <insert document author here>
Abstract: This manual describes what mitogen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mitogen/mitogen.sgml.gz

Format: postscript
Files: /usr/share/doc/mitogen/mitogen.ps.gz

Format: text
Files: /usr/share/doc/mitogen/mitogen.text.gz

Format: HTML
Index: /usr/share/doc/mitogen/html/index.html
Files: /usr/share/doc/mitogen/html/*.html
